version: "3"

services:
  wordpress:
    image: wordpress:5.6-php7.4
    enviroment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress: C:/Users/Admin/OneDrive/Máy tính/DockerLab/subSystem/wordpress
    port:
      - 8080: 80
    restart: always
    depends_on:
      - db

  db:
    image: mysql:5.7
    enviroment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123456
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db: C:/Users/Admin/OneDrive/Máy tính/DockerLab/subSystem/mysql
    restart: always

volumes:
  wordpress:
  db:
